/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import com.mycompany.bitedelivery.GuardoDatos;
import com.mycompany.bitedelivery.UsuarioEmpresa;
import com.mycompany.bitedelivery.UsuarioParticular;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaac
 */
public class MenuAdminUsuarios extends javax.swing.JFrame {
DefaultTableModel UsuariosParticulares = new DefaultTableModel();
private ArrayList<UsuarioParticular> listaUsuariosParticulares;
private ArrayList<UsuarioEmpresa> listaUsuariosEmpresas;
    /**
     * Creates new form MenuAdminUsuarios
     */
    public MenuAdminUsuarios() {
        initComponents();
        setModeloTablaParticulares();
        setDataTablaParticulares();
    }


    private void setModeloTablaParticulares(){
        //String email, String password, String nombre, Direccion direccion,TarjetaCredito tarjeta, int telefono, String DNI
String [] cabecera = {"Email", "Password", "Nombre", "Calle","Codigo Postal","Numero", "Telefono", "DNI"};
        UsuariosParticulares.setColumnIdentifiers(cabecera);
        tablaUsuariosParticulares.setModel(UsuariosParticulares);
    }
    
    private void setDataTablaParticulares(){
        //String email, String password, String nombre, Direccion direccion,TarjetaCredito tarjeta, int telefono, String DNI
        UsuariosParticulares.setRowCount(0);
        listaUsuariosParticulares = new ArrayList<>();
        GuardoDatos.saveDataParticulares();
        GuardoDatos.loadDataParticulares();
        listaUsuariosParticulares = GuardoDatos.particulares;
        for (UsuarioParticular usuarioParticular : listaUsuariosParticulares) {
           String[] datosFila = {usuarioParticular.getEmail(), usuarioParticular.getPassword(), usuarioParticular.getNombre(), usuarioParticular.getDireccion().getCalle(), String.valueOf(usuarioParticular.getDireccion().getZip()), String.valueOf(usuarioParticular.getDireccion().getNumero()), String.valueOf(usuarioParticular.getTelefono()), usuarioParticular.getDNI()};
              UsuariosParticulares.addRow(datosFila);
        }
    }
    
    private void setModeloTablaEmpresas(){
        //String email, String password, String nombre, Direccion direccion,TarjetaCredito tarjeta, int telefono, String DNI



}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuariosParticulares = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaUsuariosParticulares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuariosParticulares);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuariosParticulares;
    // End of variables declaration//GEN-END:variables
}
