/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Isaac
 */
public class ObsoletoMenuRegistrarse extends javax.swing.JFrame {
private MenuInicial principal;
    /**
     * Creates new form NewJFrame
     */
    public ObsoletoMenuRegistrarse(MenuInicial ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        initComponents();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        fondoRegistrarse = new javax.swing.JLabel();
        panelLateral = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        telefono = new javax.swing.JTextField();
        calle = new javax.swing.JTextField();
        numeroCalle = new javax.swing.JFormattedTextField();
        zip = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BiteDelivery");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 760));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        background1.setBackground(new java.awt.Color(0, 0, 0));
        background1.setMaximumSize(new java.awt.Dimension(1270, 760));
        background1.setName("BiteDelivery"); // NOI18N
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipoletras.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(971, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        background1.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 100));

        fondoRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuRegistrarse/FondoRegistrarse (Medium).jpg"))); // NOI18N
        fondoRegistrarse.setText("jLabel1");

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
            .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInferiorLayout.createSequentialGroup()
                    .addComponent(fondoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
            .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInferiorLayout.createSequentialGroup()
                    .addComponent(fondoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background1.add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 720, 660));

        panelLateral.setBackground(new java.awt.Color(255, 255, 255));

        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setText("Nombre");
        nombre.setToolTipText("nombre");
        nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFocusGained(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido.setText("Apellido");
        apellido.setToolTipText("Apellido");
        apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellidoFocusGained(evt);
            }
        });

        correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correo.setText("ejemplo@email.com");
        correo.setToolTipText("email");
        correo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoFocusLost(evt);
            }
        });

        contraseña.setText("contraseña");
        contraseña.setToolTipText("contraseña");
        contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraseñaFocusLost(evt);
            }
        });
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono.setText("Telefono");
        telefono.setToolTipText("Telefono");

        calle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        calle.setText("Calle");
        calle.setToolTipText("Calle");
        calle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        calle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                calleFocusLost(evt);
            }
        });
        calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleActionPerformed(evt);
            }
        });

        numeroCalle.setText("Numero");
        numeroCalle.setToolTipText("Numero");
        numeroCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroCalleFocusLost(evt);
            }
        });
        numeroCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCalleActionPerformed(evt);
            }
        });
        numeroCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroCalleKeyTyped(evt);
            }
        });

        zip.setText("Codigo Postal");
        zip.setToolTipText("Codigo Postal");
        zip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoPostalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoPostalFocusLost(evt);
            }
        });
        zip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoPostalKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuRegistrarse/fraseRegistrarse.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        botonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonRegistrarse.png"))); // NOI18N
        botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistroMouseExited(evt);
            }
        });

        dni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dni.setText("DNI");
        dni.setToolTipText("DNI");
        dni.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dniFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralLayout.createSequentialGroup()
                            .addComponent(contraseña)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(correo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelLateralLayout.createSequentialGroup()
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(calle, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralLayout.createSequentialGroup()
                            .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numeroCalle))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonRegistro)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(botonRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        background1.add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusGained
        // TODO add your handling code here:
        nombre.setText("");

        
    }//GEN-LAST:event_nombreFocusGained

    private void apellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidoFocusGained
        // TODO add your handling code here:
        apellido.setText("");
        
    }//GEN-LAST:event_apellidoFocusGained
    private void apellidoFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
        if(apellido.getText().equals("")){
            apellido.setText("Apellido");
        }
    }//GEN-L
    private void nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusLost
        // TODO add your handling code here:
        if(nombre.getText().equals("")){
            nombre.setText("Nombre");
        }
    }//GEN-LAST:event_nombreFocusLost

    private void correoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFocusGained
        // TODO add your handling code here:
        correo.setText("");

        
    }//GEN-LAST:event_correoFocusGained

    private void correoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFocusLost
        // TODO add your handling code here:
        if(correo.getText().equals("")){
            correo.setText("ejemplo@email.com");
        }
    }//GEN-LAST:event_correoFocusLost

    private void contraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaFocusGained
        // TODO add your handling code here:
        contraseña.setText("");
    }//GEN-LAST:event_contraseñaFocusGained

    private void contraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaFocusLost
        // TODO add your handling code here:
        if(contraseña.getText().equals("")){
            contraseña.setText("Contraseña");
        }
    }//GEN-LAST:event_contraseñaFocusLost

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contraseñaActionPerformed
    /**
     * @param args the command line arguments
     */
    //telefono focus gained
    private void telefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoFocusGained
        // TODO add your handling code here:
        telefono.setText("");
    }//GEN-LAST:event_telefonoFocusGained
    //telefono focus lost
    private void telefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoFocusLost
        // TODO add your handling code here:
        if(telefono.getText().equals("")){
            telefono.setText("Telefono");
        }
    }//GEN-LAST:event_telefonoFocusLost

    private void calleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calleFocusGained
        // TODO add your handling code here:
        calle.setText("");
    }//GEN-LAST:event_calleFocusGained

    private void calleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calleFocusLost
        // TODO add your handling code here:
        if(calle.getText().equals("")){
            calle.setText("Direccion");
        }
    }//GEN-LAST:event_calleFocusLost

    private void numeroCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCalleActionPerformed

    private void numeroCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroCalleFocusGained
        // TODO add your handling code here:
        numeroCalle.setText("");
    }//GEN-LAST:event_numeroCalleFocusGained

    private void numeroCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroCalleFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_numeroCalleFocusLost

    private void codigoPostalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoPostalFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_codigoPostalFocusGained

    private void codigoPostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoPostalFocusLost
        // TODO add your handling code here:

     
        
    }//GEN-LAST:event_codigoPostalFocusLost

    private void numeroCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroCalleKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_numeroCalleKeyTyped

    private void codigoPostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoPostalKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }

    }//GEN-LAST:event_codigoPostalKeyTyped

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void botonRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseEntered
        // TODO add your handling code here:
        botonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonRegistrarse2.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistroMouseEntered

    private void botonRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseExited
        // TODO add your handling code here:
           botonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonRegistrarse.png"))); // NOI18N
    }//GEN-LAST:event_botonRegistroMouseExited

    private void botonRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseClicked
        // TODO add your handling code here:
        String nombre = this.nombre.getText();
        String apellido = this.apellido.getText();
        String correo = this.correo.getText();
        String contraseña = this.contraseña.getText();
        int telefono = Integer.parseInt(this.telefono.getText());
        String calle = this.calle.getText();
        int numeroCalle = Integer.parseInt(this.numeroCalle.getText());

        // String ciudad = this.ciudad.getText();
       // String provincia = this.provincia.getText();
       // String pais = this.pais.getText();
        String dni = this.dni.getText();
        //String tipoUsuario = "Cliente";


    }//GEN-LAST:event_botonRegistroMouseClicked

    private void dniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dniFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dniFocusGained

    private void dniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dniFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dniFocusLost

    private void calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObsoletoMenuRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObsoletoMenuRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObsoletoMenuRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObsoletoMenuRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JPanel background1;
    private javax.swing.JLabel botonRegistro;
    private javax.swing.JTextField calle;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel fondoRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombre;
    private javax.swing.JFormattedTextField numeroCalle;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField telefono;
    private javax.swing.JFormattedTextField zip;
    // End of variables declaration//GEN-END:variables
}
